spring:
  application:
    name: edere-statistics
  datasource:
    url: jdbc:postgresql://localhost:5432/rank
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: 8899